INSERT INTO catalog_items (name, category, pvp, cost, active) VALUES
('Agua', 'bebida', 0, 0, true),
('Anchoa 00 y mantequilla trufada', 'aperitivo-frio', 0, 0, true),
('Arroz meloso de mariscos y pescados de roca', 'arroz', 9.0, 3.8, true),
('Carrillera a baja temperatura con pure de patatas trufado', 'carne', 0, 0, true),
('Carrillera a baja temperatura con pure trufado', 'carne', 0, 0, true),
('Cava brindis', 'bebida', 3.5, 1.2, true),
('Cava', 'bebida', 0, 0, true),
('Cania de lomo', 'aperitivo-frio', 0, 0, true),
('Cerveza con y sin', 'bebida', 2.5, 0.8, true),
('Cerveza con/sin', 'bebida', 0, 0, true),
('Chacinas y quesos', 'aperitivo-frio', 0, 0, true),
('Cordero a baja temperatura, patatas fritas al ajillo y su jugo', 'carne', 0, 0, true),
('Croquetas de jamon iberico', 'aperitivo-caliente', 0, 0, true),
('Empanadillas de boletus, carrillera y trufa', 'aperitivo-caliente', 0, 0, true),
('Empanadillas de ventresca de atun con tomate', 'aperitivo-caliente', 0, 0, true),
('Ensaladilla cremosa, huevo frito y gamba cristal', 'aperitivo-frio', 0, 0, true),
('Frito variado 4 tipos', 'aperitivo-frio', 0, 0, true),
('Gambas cocidas', 'pescado', 0, 0, true),
('Gorditas del sur', 'aperitivo-frio', 0, 0, true),
('Gyozas de pringa, crema de remolacha y hierbabuena', 'aperitivo-caliente', 0, 0, true),
('Lomo de bacalao confitado, espinacas ahumadas a la crema', 'pescado', 11.0, 4.5, true),
('Manzanilla', 'bebida', 0, 0, true),
('Merluza gratinada con crema de ajo asado y salsa rotena', 'pescado', 0, 0, true),
('Merluza rellena de mariscos y almejas a la marinera', 'pescado', 11.5, 4.8, true),
('Mucho chocolate', 'postre', 4.5, 1.8, true),
('Pan individual', 'aperitivo-frio', 0, 0, true),
('Papas alinas de Sanlucar', 'aperitivo-frio', 0, 0, true),
('Postre del dia', 'postre', 0, 0, true),
('Presa a la brasa, salsa al whisky, patatas fritas, padron y piquillos', 'carne', 13.5, 5.8, true),
('Queso', 'aperitivo-frio', 0, 0, true),
('Refrescos', 'bebida', 0, 0, true),
('Solomillo de vaca vieja, cremoso de patata y salsa a la pimienta negra', 'carne', 14.5, 6.2, true),
('Sorbete de limon', 'sorbete', 0, 0, true),
('Surtido de minipasteles', 'postre', 0, 0, true),
('Tarta de celebracion', 'postre', 5.0, 2.0, true),
('Tarta de queso', 'postre', 4.0, 1.5, true),
('Verdejo y Frizzante', 'bebida', 0, 0, true),
('Vino tinto Lomas del Marquez', 'bebida', 4.5, 1.8, true),
('Vino tinto', 'bebida', 0, 0, true),
('Canelon de carabinero relleno de marisco, mango y aguacate', 'compartir-mesa', 0, 0, true)
ON CONFLICT (name) DO NOTHING;
